lab4 merge finished
aghbit/Algorytmy-Geometryczne pull request #33
Opened 2023-09-04 14:26 UTC by puszekjuliuszek

2023-09-04 14:36 UTC, mdbrnowski requested changes
Warto by wyczyścić outputy w notebooku (będzie dużo łatwiej porównywać późniejsze zmiany i nie będzie tych dużych komunikatów o błędach).

Oprócz tego ten fragment kodu (we wszystkich trzech przypadkach)
```py
lab4_tester = Test()
lab4_tester.runtest(1, generate_uniform_sections)
```
można zamienić po prostu na
```py
Test().runtest(1, generate_uniform_sections)
```
bo nigdzie później z tego obiektu `lab4_tester` nie korzystamy.

2023-09-04 16:42 UTC, puszekjuliuszek commented
Słuszne uwagi już poprawiłem to o czym pisałeś

2023-09-05 08:52 UTC, mdbrnowski approved these changes

2023-09-05 12:29 UTC, radoslawrolka approved these changes

2023-09-05 13:55 UTC, Rusiek approved these changes

2023-09-05 13:55 UTC, merged