Jupiter
aghbit/Algorytmy-Geometryczne pull request #35
Opened 2023-09-12 17:05 UTC by radoslawrolka

Visualization + test connected in lab 1, 3

2023-09-12 18:22 UTC, mdbrnowski requested changes
Tak jak w #33, chyba dobrze by było wyczyścić outputy, choćby po to, żeby się te błędy o nieistnieniu jakiejś zmiennej nie pojawiały oraz żaby się łatwiej porównywało kolejne wersje pliku.

2023-09-12 19:57 UTC, radoslawrolka commented
[[1486eb5](https://github.com/aghbit/Algorytmy-Geometryczne/pull/35/commits/1486eb582dcf6978e13515cfba4e5dd6395893bc)] Output wyczyszczony oraz usunięte "WNIOSKI HERE" wspomniane na spotkaniu

2023-09-13 09:47 UTC, mdbrnowski approved these changes

2023-09-16 00:57 UTC, Rusiek approved these changes

2023-09-16 00:57 UTC, merged