Readmee
aghbit/Algorytmy-Geometryczne pull request #42
Opened 2023-09-30 14:19 UTC by jakmro

2023-10-01 10:15 UTC, mdbrnowski requested changes

2023-10-01 10:15 UTC, mdbrnowski commented on README.md
> +Algorytmy-Geometryczne$ python3 setup.py sdist
Mam wątpliwości co do sensowności tej zmiany -- użytkownik nie może już sobie po prostu tego przekopiować.

2023-10-01 10:15 UTC, mdbrnowski commented on README.md
> +Tutaj znajdują się przygotowane notebooki które musisz wypełnic. Każdy folder odpowiada jednemu laboratorium
Jak już piszemy jakieś dłuższe zdania, to może warto, żeby były poprawne interpunkcyjnie. Tutaj brakuje  przecinka przed "które". W kolejnych linijkach również brakuje kilku przecinków. Polecam [languagetool](https://languagetool.org/pl).

2023-10-01 10:15 UTC, mdbrnowski commented on README.md
> +Kod który wykonuje testy w poszczególnych notebookach znajduje się w plikach test1.py, test2.py, test3.py, test4.py.
Nazwy plików powinny wyróżniać się wśród tekstu, ja bym dodał tutaj grawisy. Np. `test1.py` zamiast test1.py.

2023-10-01 10:15 UTC, mdbrnowski commented on README.md
> +się w README (jeden paragraf wyżej) oraz warto zapoznać się z plikiem [demo.ipynb](https://github.com/aghbit/Algorytmy-Geometryczne/blob/master/bitalg/visualizer/demo.ipynb)
[błąd składniowy] Warto usunąć to "oraz" na rzecz kropki kończącej zdanie.

2023-10-02 09:24 UTC, Rusiek approved these changes

2023-10-02 09:24 UTC, merged